// server/routes/notificationRoutes.js
import express from 'express';
import multer from 'multer';
import mongoose from 'mongoose';
import path from 'path';
import fs from 'fs';
import { Notification, UserNotificationMapping } from '../models/Notification.js';
import User from '../models/User.js'; 
import nodemailer from 'nodemailer';

const router = express.Router();

// PR-FIX: Ensure directory path context exists on local host disk space
const uploadDir = path.join('uploads', 'notifications');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

// PR-FIX: Switch storage configuration from memory allocations to disk system volumes
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    // Generate distinct non-colliding file markers using current timestamps
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
    const extension = path.extname(file.originalname);
    cb(null, `${file.fieldname}-${uniqueSuffix}${extension}`);
  }
});

const upload = multer({ storage: storage }); 

// CREATE & DISPATCH NEW NOTIFICATION FORM
router.post('/dispatch', upload.array('attachments'), async (req, res) => {
  try {
    const { title, message, userIds, sendEmail, currentUserId } = req.body;
    
    const senderId = req.user?._id || currentUserId;

    if (!senderId || !mongoose.Types.ObjectId.isValid(senderId)) {
      return res.status(400).json({ success: false, message: 'Invalid or missing Sender Session Identity Context.' });
    }

    let parsedUserIds = [];
    if (typeof userIds === 'string') {
      try {
        parsedUserIds = JSON.parse(userIds);
      } catch (e) {
        parsedUserIds = userIds.split(',').map(id => id.trim());
      }
    } else if (Array.isArray(userIds)) {
      parsedUserIds = userIds;
    }

    parsedUserIds = parsedUserIds.filter(id => mongoose.Types.ObjectId.isValid(id));

    if (!parsedUserIds.length) {
      return res.status(400).json({ success: false, message: 'Please designate at least one active recipient with a valid ID.' });
    }

    const shouldSendEmail = sendEmail === 'true' || sendEmail === true;

    // PR-FIX: Read path destinations generated by diskStorage and build accessible web links
    const processedAttachments = (req.files || []).map(file => ({
      fileName: file.originalname,
      // Converts local systems directory syntax to clear client URL endpoints
      fileUrl: `/uploads/notifications/${file.filename}`, 
      mimeType: file.mimetype
    }));

    // 1. Persist primary advisory metadata block WITH dynamic senderId and receiverIds array
    const newNotification = await Notification.create({
      senderId: new mongoose.Types.ObjectId(senderId),
      title,
      message,
      attachments: processedAttachments,
      receiverIds: parsedUserIds.map(id => new mongoose.Types.ObjectId(id)),
      sentViaEmail: shouldSendEmail
    });

    // 2. Generate individual user mapping entries for tracking read/unread statuses
    const recipientRecords = parsedUserIds.map(userId => ({
      notificationId: newNotification._id,
      userId: new mongoose.Types.ObjectId(userId),
      isRead: false
    }));
    
    await UserNotificationMapping.insertMany(recipientRecords);

    // 3. NodeMailer Email pipeline
    if (shouldSendEmail) {
      const targetUsers = await User.find({ _id: { $in: parsedUserIds } });
      const emails = targetUsers.map(u => u.email).filter(Boolean);

      if (emails.length > 0) {
        let transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST,
          port: process.env.SMTP_PORT,
          auth: { 
            user: process.env.SMTP_USER, 
            pass: process.env.SMTP_PASS 
          },
          tls: {
            rejectUnauthorized: false
          }
        });

        // PR-FIX: Read files directly from the hard drive space location context
        const emailAttachments = (req.files || []).map(file => ({
          filename: file.originalname,
          path: file.path, 
          contentType: file.mimetype
        }));

        await transporter.sendMail({
          from: process.env.FROM_EMAIL || '"Bridgeview Admin" <alerts@bridgeview.internal>',
          to: emails.join(','),
          subject: `[Advisory] ${title}`,
          text: message,
          attachments: emailAttachments
        });
      }
    }

    // 4. Real-time WebSocket event broadcast engine pipeline
    const io = req.app.get('socketio');
    if (io) {
      parsedUserIds.forEach(userId => {
        io.to(`user-${userId}`).emit('new-direct-notification', {
          id: newNotification._id,
          title,
          message,
          attachments: processedAttachments,
          createdAt: newNotification.createdAt
        });
      });
    }

    res.status(201).json({ 
      success: true, 
      notificationId: newNotification._id, 
      senderId,
      mappedRecipients: parsedUserIds.length 
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET CURRENT USER'S HISTORY LIST (WITH SUPER_ADMIN BYPASS)
router.get('/my-history', async (req, res) => {
  try {
    const { userId, role } = req.query; 

    if (!mongoose.Types.ObjectId.isValid(userId)) {
      return res.status(400).json({ 
        success: false, 
        error: "Invalid User ID format. Must be a 24-character hex string." 
      });
    }

    let queryFilter = { userId: new mongoose.Types.ObjectId(userId) };
    if (role === 'SUPER_ADMIN' || role === 'Super Administrator') {
      queryFilter = {}; 
    }

    const history = await UserNotificationMapping.find(queryFilter)
      .populate({
        path: 'notificationId',
        populate: { path: 'senderId', select: 'first_name last_name email role_name' }
      })
      .populate('userId', 'first_name last_name email role_name')
      .sort({ _id: -1 });

    res.status(200).json(history);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// MARK NOTIFICATION AS SEEN / READ BY USER
router.patch('/mark-read/:id', async (req, res) => {
  try {
    const updatedMapping = await UserNotificationMapping.findByIdAndUpdate(
      req.params.id,
      { isRead: true, readAt: new Date() },
      { new: true }
    );

    if (!updatedMapping) {
      return res.status(404).json({ success: false, error: "Notification record mapping log entry not found." });
    }

    res.status(200).json({ success: true, data: updatedMapping });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

export default router;