import mongoose from 'mongoose';

// Legacy MySQL table `mobile_recharge`, migrated as-is into collection_mobile_recharge.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    user: String,
    recharge_date: String,
    expiry_date: String,
    screenshot: String,
    cdate: String,
    amount: Number,
  },
  { strict: false, collection: 'collection_mobile_recharge' }
);

export const LegacyMobileRecharge = mongoose.models.LegacyMobileRecharge || mongoose.model('LegacyMobileRecharge', schema);
