import mongoose from 'mongoose';

// Legacy MySQL table `prequisition`, migrated as-is into collection_prequisition.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard
//   - Vendor > Purchase Requisition

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    iname: String,
    svendor: String,
    wpurchase: String,
    ecofcomp: String,
    cdate: String,
    userid: Number,
  },
  { strict: false, collection: 'collection_prequisition' }
);

export const LegacyPrequisition = mongoose.models.LegacyPrequisition || mongoose.model('LegacyPrequisition', schema);
