import mongoose from 'mongoose';

// Legacy MySQL table `nrpa_invoice`, migrated as-is into collection_nrpa_invoice.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    invoiceno: Number,
    invid: Number,
    po_number: String,
    invoicefor: String,
    officer_name: String,
    officer_email: String,
    officer_phone: String,
    contract_id: String,
    vcan_id: String,
    fullname: String,
    passport: String,
    rankname: String,
    jdate: String,
    jjdate: String,
    description: String,
    joiner_type: String,
    vesselname: String,
    dayson_vessel: Number,
    rate: String,
    agencyfee: Number,
    other: Number,
    doe: String,
    sort: String,
    bank_id: String,
    payment_date: String,
    status: String,
    doneby: String,
    total: String,
    user: String,
    company_name: String,
    companyid: Number,
    invoic_no: String,
    creferenceno: String,
    crewl_fee: String,
    istatus: String,
    lockeds: Number,
    sentid: String,
    invunlockreq: Number,
    invunlockreqby: String,
    invunlockremark: String,
    cancelinvoice: Number,
    canceledby: String,
    cancelremarks: String,
    canceldate: String,
    invoice_raised: Number,
    update_at: String,
    update_by: String,
    approval: Number,
    approveby: String,
  },
  { strict: false, collection: 'collection_nrpa_invoice' }
);

export const LegacyNrpaInvoice = mongoose.models.LegacyNrpaInvoice || mongoose.model('LegacyNrpaInvoice', schema);
