import mongoose from 'mongoose';

// Legacy MySQL table `visitors`, migrated as-is into collection_visitors.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard
//   - Utilities > Visitor Entries

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    v_type: String,
    v_joinertype: String,
    v_indosno: String,
    v_passport: String,
    v_cdc: String,
    v_rank: String,
    v_dob: String,
    v_fullname: String,
    v_email: String,
    v_phoneno: String,
    v_alternate: String,
    v_reason: String,
    v_person: String,
    v_file: String,
    v_date: String,
    v_email_sent: Number,
    is_tmp: String,
  },
  { strict: false, collection: 'collection_visitors' }
);

export const LegacyVisitors = mongoose.models.LegacyVisitors || mongoose.model('LegacyVisitors', schema);
