import mongoose from 'mongoose';

// Legacy MySQL table `log_candidate`, migrated as-is into collection_log_candidate.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Letter Details > LG Details

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    indosno: String,
    airport_name: String,
    doi: String,
    travel_detail: String,
    travel_to: String,
    stay_place: String,
    joining_vessel: String,
    doneby: String,
    user: String,
    doe: String,
  },
  { strict: false, collection: 'collection_log_candidate' }
);

export const LegacyLogCandidate = mongoose.models.LegacyLogCandidate || mongoose.model('LegacyLogCandidate', schema);
