import mongoose from 'mongoose';

// Legacy MySQL table `bdevelopment`, migrated as-is into collection_bdevelopment.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Owner > Prospective Client

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    bid: Number,
    company_name: String,
    contact_person: String,
    contact_number: String,
    location: String,
    country: String,
    emailid: String,
    bcategory: String,
    remark: String,
    address: String,
    bdate: String,
    buser: String,
    bstatus: Number,
    bdreason: String,
    bddelete: String,
    bfrom: String,
  },
  { strict: false, collection: 'collection_bdevelopment' }
);

export const LegacyBdevelopment = mongoose.models.LegacyBdevelopment || mongoose.model('LegacyBdevelopment', schema);
