import mongoose from 'mongoose';

// Legacy MySQL table `cook_category`, migrated as-is into collection_cook_category.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Sourcing > View Candidate CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    cookid: Number,
    cookskill: String,
  },
  { strict: false, collection: 'collection_cook_category' }
);

export const LegacyCookCategory = mongoose.models.LegacyCookCategory || mongoose.model('LegacyCookCategory', schema);
