import mongoose from 'mongoose';

// Legacy MySQL table `tarbook`, migrated as-is into collection_tarbook.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - DG > Verification Of TAR Book

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    tar_scrnshot: String,
    users: String,
    status: String,
    tar_remark: String,
    indosno: String,
    contractid: String,
    emp_remark: String,
    new_remark: String,
    supuser: String,
  },
  { strict: false, collection: 'collection_tarbook' }
);

export const LegacyTarbook = mongoose.models.LegacyTarbook || mongoose.model('LegacyTarbook', schema);
