import mongoose from 'mongoose';

// Legacy MySQL table `otpemail`, migrated as-is into collection_otpemail.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Staff Member List
//   - DG > Issuance of Sea-Service
//   - Report > Candidate Information

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    name: String,
    email: String,
  },
  { strict: false, collection: 'collection_otpemail' }
);

export const LegacyOtpemail = mongoose.models.LegacyOtpemail || mongoose.model('LegacyOtpemail', schema);
