import mongoose from 'mongoose';

// Legacy MySQL table `invoice_confirmation`, migrated as-is into collection_invoice_confirmation.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    category: String,
    invid: String,
    username: String,
    confirm: Number,
    remark: String,
    date: String,
  },
  { strict: false, collection: 'collection_invoice_confirmation' }
);

export const LegacyInvoiceConfirmation = mongoose.models.LegacyInvoiceConfirmation || mongoose.model('LegacyInvoiceConfirmation', schema);
