import mongoose from 'mongoose';

// Legacy MySQL table `inword_doc`, migrated as-is into collection_inword_doc.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Task For Documentation

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    doc_id: Number,
    email: String,
    indosno: String,
    inword_type: String,
    other_person: String,
    other_person_aadhar: String,
    doc_name: String,
    cdate: String,
    addby: String,
    otp: Number,
    verify: Number,
    status: Number,
    handover_remark: String,
    handover_date: String,
  },
  { strict: false, collection: 'collection_inword_doc' }
);

export const LegacyInwordDoc = mongoose.models.LegacyInwordDoc || mongoose.model('LegacyInwordDoc', schema);
