import mongoose from 'mongoose';

// Legacy MySQL table `priocheck`, migrated as-is into collection_priocheck.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    pid: Number,
    indosno: String,
    userid: Number,
    process: String,
    stage1: String,
    stage1d: String,
    stage2: String,
    stage2d: String,
    stage3: String,
    stage3d: String,
    approvaldate: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_priocheck' }
);

export const LegacyPriocheck = mongoose.models.LegacyPriocheck || mongoose.model('LegacyPriocheck', schema);
