import mongoose from 'mongoose';

// Legacy MySQL table `last_audit_report`, migrated as-is into collection_last_audit_report.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Owner > List of Owner

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    lar_year: Number,
    uplod: String,
    document_type: String,
    report: String,
    cdate: String,
    user: String,
    comid: Number,
    status: String,
  },
  { strict: false, collection: 'collection_last_audit_report' }
);

export const LegacyLastAuditReport = mongoose.models.LegacyLastAuditReport || mongoose.model('LegacyLastAuditReport', schema);
