import mongoose from 'mongoose';

// Legacy MySQL table `cms_submenu`, migrated as-is into collection_cms_submenu.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    submenu_id: Number,
    submenu_name: String,
    page_name: String,
    menu_id: Number,
    status: Number,
  },
  { strict: false, collection: 'collection_cms_submenu' }
);

export const LegacyCmsSubmenu = mongoose.models.LegacyCmsSubmenu || mongoose.model('LegacyCmsSubmenu', schema);
