import mongoose from 'mongoose';

// Legacy MySQL table `email`, migrated as-is into collection_email.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - Report > Candidate Information

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    companyname: String,
    emailid: String,
  },
  { strict: false, collection: 'collection_email' }
);

export const LegacyEmail = mongoose.models.LegacyEmail || mongoose.model('LegacyEmail', schema);
