import mongoose from 'mongoose';

// Legacy MySQL table `ipaddress`, migrated as-is into collection_ipaddress.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    ipid: Number,
    username: String,
    ipaddress: String,
    itime: String,
  },
  { strict: false, collection: 'collection_ipaddress' }
);

export const LegacyIpaddress = mongoose.models.LegacyIpaddress || mongoose.model('LegacyIpaddress', schema);
