import mongoose from 'mongoose';

// Legacy MySQL table `certificatecoc`, migrated as-is into collection_certificatecoc.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Sourcing > View Candidate CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    certificate: String,
    country: String,
    type: String,
    status: Number,
  },
  { strict: false, collection: 'collection_certificatecoc' }
);

export const LegacyCertificatecoc = mongoose.models.LegacyCertificatecoc || mongoose.model('LegacyCertificatecoc', schema);
