import mongoose from 'mongoose';

// Legacy MySQL table `questionbank`, migrated as-is into collection_questionbank.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Sourcing > View Candidate CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    question: String,
    eng_que: String,
    indosno: String,
    rank: String,
    company: Number,
    emailid: String,
    cdate: String,
    sid: Number,
    status: Number,
  },
  { strict: false, collection: 'collection_questionbank' }
);

export const LegacyQuestionbank = mongoose.models.LegacyQuestionbank || mongoose.model('LegacyQuestionbank', schema);
