import mongoose from 'mongoose';

// Legacy MySQL table `companyinvoice_followup`, migrated as-is into collection_companyinvoice_followup.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Company Invoice Followup

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    company: Number,
    category: String,
    inv_number: String,
    gen_date: String,
    amount: Number,
    invoice_copy: String,
    remark: String,
    cdate: String,
    addby: String,
    payment: String,
    half_payment: String,
    payment_date: String,
    payment_screenshot: String,
    update_by: String,
    update_date: String,
    status: Number,
  },
  { strict: false, collection: 'collection_companyinvoice_followup' }
);

export const LegacyCompanyinvoiceFollowup = mongoose.models.LegacyCompanyinvoiceFollowup || mongoose.model('LegacyCompanyinvoiceFollowup', schema);
