import mongoose from 'mongoose';

// Legacy MySQL table `bankaccounts`, migrated as-is into collection_bankaccounts.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Bank Details

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    account_name: String,
    bank_name: String,
    bank_address: String,
    account_number: String,
    account_type: String,
    rtgs_neft_ifsc: String,
    swift_code: String,
    pan_no: String,
    status: Number,
  },
  { strict: false, collection: 'collection_bankaccounts' }
);

export const LegacyBankaccounts = mongoose.models.LegacyBankaccounts || mongoose.model('LegacyBankaccounts', schema);
