import mongoose from 'mongoose';

// Legacy MySQL table `visiter`, migrated as-is into collection_visiter.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > DG Related Icon
//   - Documentation > Document Upload
//   - Documentation > List of cancelled Joiners
//   - Documentation > Task For Documentation
//   - Documentation > Travel Diary
//   - Home > Dashboard
//   - Invoice > Proforma Invoice
//   - NRPA > Data Submit For eMigrate
//   - Report > Back Out Candidate
//   - Report > Signoff Data Reports
//   - Sourcing > View Candidate CV
//   - Utilities > Flag Document
//   - Utilities > Hotel Request
//   - Utilities > Medical Request
//   - Utilities > PPE Request

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    vs_id: Number,
    name: String,
    email: String,
    mobile: String,
    indosno: String,
    passport: String,
    rankname: String,
    purpose: String,
    cdc: String,
    coc: String,
    salary: String,
    document: String,
    image: String,
    passport_upload: String,
    cdc_upload: String,
    type: String,
    addedby: String,
    documentsr: String,
    residance_visa: Number,
    sea_panel: Number,
    contract_panel: Number,
    dstatus: String,
    dremark: String,
    company_ban: String,
    status: Number,
    doe: String,
    cvcategory: String,
    cms_email: Number,
    aadharno: String,
    pancardno: String,
    sidno: String,
    dp_license: String,
    phone_code: String,
    child_type: String,
    child: String,
    dobc: String,
  },
  { strict: false, collection: 'collection_visiter' }
);

export const LegacyVisiter = mongoose.models.LegacyVisiter || mongoose.model('LegacyVisiter', schema);
