import mongoose from 'mongoose';

// Legacy MySQL table `companyreg`, migrated as-is into collection_companyreg.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - NRPA > Other Nationality Crew
//   - Shore Job > Shore Candidate All CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    comid: Number,
    uname: String,
    contactperson: String,
    password: String,
    repassword: String,
    company: String,
    email: String,
    website: String,
    countryname: String,
    state: String,
    city: String,
    address: String,
    mobileno: String,
    photo: String,
    orderid: String,
    plan_status: String,
    plan_id: String,
    plan_postjob: String,
    plan_view: String,
    plan_pdf: String,
    plan_word: String,
    plan_expiry: String,
    cdate: String,
    status: String,
  },
  { strict: false, collection: 'collection_companyreg' }
);

export const LegacyCompanyreg = mongoose.models.LegacyCompanyreg || mongoose.model('LegacyCompanyreg', schema);
