import mongoose from 'mongoose';

// Legacy MySQL table `invoice`, migrated as-is into collection_invoice.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard
//   - Invoice > Print Invoice

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    invoiceno: Number,
    invid: Number,
    po_number: String,
    jobid: String,
    vcan_id: String,
    fullname: String,
    invoicefor: String,
    passport: String,
    dayson_vessel: Number,
    agencyfee: Number,
    finder_fee: Number,
    salary_ret: Number,
    exrate: String,
    other: Number,
    medical_amount: Number,
    hts: Number,
    brm: Number,
    huet: Number,
    visa_amount: Number,
    travel_amount: Number,
    visa_cancelation: Number,
    doe: String,
    sort: String,
    bank_id: String,
    payment_date: String,
    status: String,
    doneby: String,
    total: String,
    certificate_amount: Number,
    user: String,
    rankname: String,
    company_name: String,
    companyid: Number,
    vesselname: String,
    joiner_type: String,
    hamount: Number,
    invoic_no: String,
    increment: Number,
    creferenceno: String,
    crewl_fee: String,
    jdate: String,
    jjdate: String,
    fromdate: String,
    todate: String,
    istatus: String,
    lockeds: Number,
    sentid: String,
    invunlockreq: Number,
    invunlockreqby: String,
    invunlockremark: String,
    cancelinvoice: Number,
    canceledby: String,
    cancelremarks: String,
    canceldate: String,
    invoice_raised: String,
    invoice_sent: String,
    invoice_payed: String,
    update_at: String,
    update_by: String,
  },
  { strict: false, collection: 'collection_invoice' }
);

export const LegacyInvoice = mongoose.models.LegacyInvoice || mongoose.model('LegacyInvoice', schema);
