import mongoose from 'mongoose';

// Legacy MySQL table `currency`, migrated as-is into collection_currency.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > List of cancelled Joiners
//   - Documentation > Task For Documentation
//   - Home > Dashboard
//   - Sourcing > Task For Sourcing
//   - Sourcing > View Candidate CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    cu_id: Number,
    currency_type: String,
    rate: Number,
    status: String,
  },
  { strict: false, collection: 'collection_currency' }
);

export const LegacyCurrency = mongoose.models.LegacyCurrency || mongoose.model('LegacyCurrency', schema);
