import mongoose from 'mongoose';

// Legacy MySQL table `categ_shiptype`, migrated as-is into collection_categ_shiptype.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Generate Invoice

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    c_st: Number,
    ship_type: String,
    status: String,
  },
  { strict: false, collection: 'collection_categ_shiptype' }
);

export const LegacyCategShiptype = mongoose.models.LegacyCategShiptype || mongoose.model('LegacyCategShiptype', schema);
