import mongoose from 'mongoose';

// Legacy MySQL table `notice`, migrated as-is into collection_notice.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Utilities > My Files

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    txt_name: String,
    txt_notice: String,
    department: String,
    txt_fromdate: String,
    txt_tilldate: String,
    txt_file: String,
    cdate: String,
    user: String,
    status: Number,
  },
  { strict: false, collection: 'collection_notice' }
);

export const LegacyNotice = mongoose.models.LegacyNotice || mongoose.model('LegacyNotice', schema);
