import mongoose from 'mongoose';

// Legacy MySQL table `dyn_crew`, migrated as-is into collection_dyn_crew.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Pooled Crew

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    companyid: Number,
    crew_type: String,
    crew_name: String,
    crew_phone: String,
    crew_email: String,
    crew_expire: String,
  },
  { strict: false, collection: 'collection_dyn_crew' }
);

export const LegacyDynCrew = mongoose.models.LegacyDynCrew || mongoose.model('LegacyDynCrew', schema);
