import mongoose from 'mongoose';

// Legacy MySQL table `editvacancies`, migrated as-is into collection_editvacancies.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Rejoining Vacancies
//   - Shore Job > Add Shore Vacancy
//   - Sourcing > Deleted/Closed Vacancies
//   - Sourcing > List of vacancies

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    dov: String,
    company_name: String,
    crew_name: String,
    rankname: String,
    noopening: Number,
    salary: String,
    visatype: String,
    editremark: String,
    remark: String,
    jlocation: String,
    cduration: Number,
    vesseltype: String,
    exp: String,
    excrew: String,
    details: String,
    vessel_id: String,
    addby: String,
    ship_type: String,
    v_id: String,
    currency_type: String,
    type_days: String,
    shsub_id: String,
    user: String,
    image: String,
    assignby: String,
    assignto: String,
    doc: String,
    eid: Number,
    eiddate: String,
    eidby: String,
  },
  { strict: false, collection: 'collection_editvacancies' }
);

export const LegacyEditvacancies = mongoose.models.LegacyEditvacancies || mongoose.model('LegacyEditvacancies', schema);
