import mongoose from 'mongoose';

// Legacy MySQL table `visaservice`, migrated as-is into collection_visaservice.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    dateorr: String,
    company: Number,
    name: String,
    passport: String,
    visatype: String,
    vendor: Number,
    dateva: String,
    datevr: String,
    compcurr: String,
    amountcompany: Number,
    vencurr: String,
    amountvendor: Number,
    addedby: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_visaservice' }
);

export const LegacyVisaservice = mongoose.models.LegacyVisaservice || mongoose.model('LegacyVisaservice', schema);
