import mongoose from 'mongoose';

// Legacy MySQL table `cms_actions_user`, migrated as-is into collection_cms_actions_user.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - Owner > List of Owner
//   - Report > Candidate Information

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    cms_action: Number,
    submenu_id: Number,
    user: String,
    status: Number,
    doneby: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_cms_actions_user' }
);

export const LegacyCmsActionsUser = mongoose.models.LegacyCmsActionsUser || mongoose.model('LegacyCmsActionsUser', schema);
