import mongoose from 'mongoose';

// Legacy MySQL table `document_logs`, migrated as-is into collection_document_logs.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    stage: String,
    remarks: String,
    indosno: String,
    companyid: Number,
    vacancyid: Number,
    username: String,
    logdate: String,
  },
  { strict: false, collection: 'collection_document_logs' }
);

export const LegacyDocumentLogs = mongoose.models.LegacyDocumentLogs || mongoose.model('LegacyDocumentLogs', schema);
