import mongoose from 'mongoose';

// Legacy MySQL table `coscertificate`, migrated as-is into collection_coscertificate.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - Home > Dashboard
//   - Letter Details > Old Sea Service

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    cos_refno: String,
    cosrno: Number,
    prefix: String,
    cos_candname: String,
    cos_rank: String,
    cos_passport: String,
    cos_indos: String,
    contract_id: Number,
    cos_date: String,
    cos_cdc: String,
    cos_owner: String,
    cos_vessel: String,
    flag: String,
    cos_fleettype: String,
    cos_shiptype: String,
    cos_fromdate: String,
    cos_todate: String,
    cos_grt: String,
    cos_nrt: String,
    cos_kwt: String,
    conduct: String,
    ability: String,
    sobriety: String,
    addby: String,
    adddate: String,
    editby: String,
    editdate: String,
    status: String,
    email: String,
    remark: String,
    voyage: String,
    imo: String,
    address: String,
    mmd: String,
    address1: String,
    address2: String,
    address3: String,
    cos_area: String,
    director: String,
    cv_id: Number,
    attach_file: String,
    attach_pass: String,
    attach_dg: String,
    rq_date: String,
    lines2: String,
    lines1: String,
    cos_status: String,
    cos_subto: String,
    cos_substatus: String,
    cos_subby: String,
    cos_subdate: String,
    cos_subremark: String,
    cos_auser: String,
    app_date: String,
    cos_type: String,
    cos_user: String,
    cos_print: String,
    print_date: String,
    priority: String,
    "Column 54": String,
    cos_correction: String,
    candidate_feedback: String,
    passport_left_scrnshot: String,
    passport_right_scrnshot: String,
    cdc_scrnshot: String,
    dg_scrnshot: String,
    deactivate_reason: String,
  },
  { strict: false, collection: 'collection_coscertificate' }
);

export const LegacyCoscertificate = mongoose.models.LegacyCoscertificate || mongoose.model('LegacyCoscertificate', schema);
