import mongoose from 'mongoose';

// Legacy MySQL table `dispatched_doc_sea_service`, migrated as-is into collection_dispatched_doc_sea_service.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - Utilities > In/Out Documents

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    indos_no: String,
    cosr_no: String,
    dispatched_type: String,
    dispatched_code: String,
    dispatched_remark: String,
    duration_from: String,
    duration_to: String,
    added_by: String,
    added_date: String,
    status: Number,
  },
  { strict: false, collection: 'collection_dispatched_doc_sea_service' }
);

export const LegacyDispatchedDocSeaService = mongoose.models.LegacyDispatchedDocSeaService || mongoose.model('LegacyDispatchedDocSeaService', schema);
