import mongoose from 'mongoose';

// Legacy MySQL table `listofholiday`, migrated as-is into collection_listofholiday.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    holidays: String,
    day: String,
    date: String,
    status: Number,
  },
  { strict: false, collection: 'collection_listofholiday' }
);

export const LegacyListofholiday = mongoose.models.LegacyListofholiday || mongoose.model('LegacyListofholiday', schema);
