import mongoose from 'mongoose';

// Legacy MySQL table `bo_country`, migrated as-is into collection_bo_country.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    countryname: String,
    status: String,
  },
  { strict: false, collection: 'collection_bo_country' }
);

export const LegacyBoCountry = mongoose.models.LegacyBoCountry || mongoose.model('LegacyBoCountry', schema);
