import mongoose from 'mongoose';

// Legacy MySQL table `ship_subcat`, migrated as-is into collection_ship_subcat.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Rejoining Vacancies
//   - Home > Dashboard
//   - Shore Job > Add Shore Vacancy
//   - Sourcing > List of vacancies
//   - Sourcing > Task For Sourcing

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    shsub_id: Number,
    subcat_name: String,
    c_st: String,
    status: String,
  },
  { strict: false, collection: 'collection_ship_subcat' }
);

export const LegacyShipSubcat = mongoose.models.LegacyShipSubcat || mongoose.model('LegacyShipSubcat', schema);
