import mongoose from 'mongoose';

// Legacy MySQL table `other_expenses`, migrated as-is into collection_other_expenses.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Other Expenses

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    oid: Number,
    req_date: String,
    req_by: String,
    payment_by: String,
    company: Number,
    vendor: Number,
    product: String,
    product_details: String,
    amount_vendor: String,
    vendor_payment: String,
    amount_company: String,
    company_payment: String,
    email_sent: Number,
    added_by: String,
    added_date: String,
    status: Number,
  },
  { strict: false, collection: 'collection_other_expenses' }
);

export const LegacyOtherExpenses = mongoose.models.LegacyOtherExpenses || mongoose.model('LegacyOtherExpenses', schema);
