import mongoose from 'mongoose';

// Legacy MySQL table `hotel_request`, migrated as-is into collection_hotel_request.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Utilities > Hotel Request

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    hotelid: Number,
    vendor: Number,
    req_date: String,
    payment_by: String,
    company: Number,
    email: String,
    indosno: String,
    checkin: String,
    checkout: String,
    room: String,
    meal: String,
    remark: String,
    paidto_bmpl: String,
    paidto_vendor: String,
    doneby: String,
    cdate: String,
    status: Number,
  },
  { strict: false, collection: 'collection_hotel_request' }
);

export const LegacyHotelRequest = mongoose.models.LegacyHotelRequest || mongoose.model('LegacyHotelRequest', schema);
