import mongoose from 'mongoose';

// Legacy MySQL table `cv_deletion`, migrated as-is into collection_cv_deletion.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Sourcing > View Candidate CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    resumeid: Number,
    user: String,
    cdate: String,
    status: Number,
  },
  { strict: false, collection: 'collection_cv_deletion' }
);

export const LegacyCvDeletion = mongoose.models.LegacyCvDeletion || mongoose.model('LegacyCvDeletion', schema);
