import mongoose from 'mongoose';

// Legacy MySQL table `engine_type`, migrated as-is into collection_engine_type.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    engine_type: String,
    status: Number,
  },
  { strict: false, collection: 'collection_engine_type' }
);

export const LegacyEngineType = mongoose.models.LegacyEngineType || mongoose.model('LegacyEngineType', schema);
