import mongoose from 'mongoose';

// Legacy MySQL table `users_menu_chatbot`, migrated as-is into collection_users_menu_chatbot.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    from_code: String,
    __v: Number,
    createdAt: mongoose.Schema.Types.Mixed,
    description: String,
    role: String,
    route: String,
    status: String,
    updatedAt: mongoose.Schema.Types.Mixed,
    user_id: String,
  },
  { strict: false, collection: 'collection_users_menu_chatbot' }
);

export const LegacyUsersMenuChatbot = mongoose.models.LegacyUsersMenuChatbot || mongoose.model('LegacyUsersMenuChatbot', schema);
