import mongoose from 'mongoose';

// Legacy MySQL table `manning_contract_copy`, migrated as-is into collection_manning_contract_copy.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Owner > List of Owner

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    valid_from: String,
    valid_till: String,
    audit_year: Number,
    uplod: String,
    user: String,
    comid: Number,
    cdate: String,
    status: Number,
  },
  { strict: false, collection: 'collection_manning_contract_copy' }
);

export const LegacyManningContractCopy = mongoose.models.LegacyManningContractCopy || mongoose.model('LegacyManningContractCopy', schema);
