import mongoose from 'mongoose';

// Legacy MySQL table `shore_rank`, migrated as-is into collection_shore_rank.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Shore Job > Add Shore Vacancy
//   - Shore Job > Shore Candidate All CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    rankname: String,
    status: Number,
  },
  { strict: false, collection: 'collection_shore_rank' }
);

export const LegacyShoreRank = mongoose.models.LegacyShoreRank || mongoose.model('LegacyShoreRank', schema);
