import mongoose from 'mongoose';

// Legacy MySQL table `signonadmin`, migrated as-is into collection_signonadmin.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Staff Member List
//   - Documentation > List of cancelled Joiners
//   - Documentation > Rejoining Vacancies
//   - Documentation > Task For Documentation
//   - Shore Job > Add Shore Vacancy
//   - Sourcing > Candidate Proposal Status
//   - Sourcing > Deleted/Closed Vacancies
//   - Sourcing > List of vacancies
//   - Vendor > Purchase Requisition

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    sign_id: Number,
    sign_name: String,
  },
  { strict: false, collection: 'collection_signonadmin' }
);

export const LegacySignonadmin = mongoose.models.LegacySignonadmin || mongoose.model('LegacySignonadmin', schema);
