import mongoose from 'mongoose';

// Legacy MySQL table `visatype`, migrated as-is into collection_visatype.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Task For Documentation
//   - Vendor > Vendor Details

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    visatype: String,
    addby: String,
    adddate: String,
    status: Number,
    deactive_reason: String,
  },
  { strict: false, collection: 'collection_visatype' }
);

export const LegacyVisatype = mongoose.models.LegacyVisatype || mongoose.model('LegacyVisatype', schema);
