import mongoose from 'mongoose';

// Legacy MySQL table `flagdoc_new`, migrated as-is into collection_flagdoc_new.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Utilities > Flag Document

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    flag: Number,
    req_date: String,
    apl_date: String,
    req_by: String,
    payment_by: String,
    indosno: String,
    emailid: String,
    vendor: String,
    company: Number,
    screen_ss: String,
    vesselname: String,
    jobid: Number,
    certificate: String,
    amount: String,
    rate: String,
    addby: String,
    start_date: String,
    end_date: String,
    cdate: String,
    paidto_bmpl: String,
    paidto_vendor: String,
    directto_vendor: Number,
    certificate_status: String,
    inout_id: Number,
    updateby: String,
    updatedate: String,
    status: Number,
    vendorinvoice_followup: Number,
  },
  { strict: false, collection: 'collection_flagdoc_new' }
);

export const LegacyFlagdocNew = mongoose.models.LegacyFlagdocNew || mongoose.model('LegacyFlagdocNew', schema);
