import mongoose from 'mongoose';

// Legacy MySQL table `vendorinvoice_followup`, migrated as-is into collection_vendorinvoice_followup.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Vendor Invoice Followup

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    vendor: Number,
    category: String,
    company: String,
    employee: String,
    device: String,
    inv_number: String,
    gen_date: String,
    rec_date: String,
    amount: String,
    payment_date: String,
    invoice_copy: String,
    remark: String,
    candidates: String,
    category_id: String,
    cdate: String,
    addby: String,
    invoice_raised: Number,
    payment: String,
    half_payment: String,
    payment_method: String,
    payment_by: String,
    payment_paid_date: String,
    payment_screenshot: String,
    update_by: String,
    update_date: String,
    status: Number,
  },
  { strict: false, collection: 'collection_vendorinvoice_followup' }
);

export const LegacyVendorinvoiceFollowup = mongoose.models.LegacyVendorinvoiceFollowup || mongoose.model('LegacyVendorinvoiceFollowup', schema);
