import mongoose from 'mongoose';

// Legacy MySQL table `vaccination_card`, migrated as-is into collection_vaccination_card.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Immunization Card

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    prefix: String,
    name: String,
    rank: String,
    email: String,
    indosno: String,
    passport: String,
    cdcno: String,
    dob: String,
    vaccination_dose: String,
    vaccine_name: String,
    takendate: String,
    vaccine_name2: String,
    takendate2: String,
    company: Number,
    vessel: String,
    director: String,
    approval: Number,
    approveby: String,
    issue_status: String,
    doneby: String,
    cdate: String,
    status: Number,
  },
  { strict: false, collection: 'collection_vaccination_card' }
);

export const LegacyVaccinationCard = mongoose.models.LegacyVaccinationCard || mongoose.model('LegacyVaccinationCard', schema);
