import mongoose from 'mongoose';

// Legacy MySQL table `licensedetails`, migrated as-is into collection_licensedetails.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > My License

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    licensename: String,
    licenseupload: String,
    licenseno: String,
    licensedoi: String,
    licensedoe: String,
    addedby: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_licensedetails' }
);

export const LegacyLicensedetails = mongoose.models.LegacyLicensedetails || mongoose.model('LegacyLicensedetails', schema);
