import mongoose from 'mongoose';

// Legacy MySQL table `proformainvoice`, migrated as-is into collection_proformainvoice.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Proforma Invoice

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    pro_id: Number,
    pro_indosno: String,
    pro_companyname: String,
    pro_rankname: String,
    pro_date: String,
    pro_invoiceno: String,
  },
  { strict: false, collection: 'collection_proformainvoice' }
);

export const LegacyProformainvoice = mongoose.models.LegacyProformainvoice || mongoose.model('LegacyProformainvoice', schema);
