import mongoose from 'mongoose';

// Legacy MySQL table `pprequisition`, migrated as-is into collection_pprequisition.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    ppid: Number,
    purchaseid: Number,
    signonid: Number,
    ppdate: String,
  },
  { strict: false, collection: 'collection_pprequisition' }
);

export const LegacyPprequisition = mongoose.models.LegacyPprequisition || mongoose.model('LegacyPprequisition', schema);
