import mongoose from 'mongoose';

// Legacy MySQL table `chatbox`, migrated as-is into collection_chatbox.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Task For Documentation

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    me: String,
    user: String,
    resumeid: Number,
    emailid: String,
    cindosno: String,
    chat: String,
    date: String,
    via: String,
    category: String,
  },
  { strict: false, collection: 'collection_chatbox' }
);

export const LegacyChatbox = mongoose.models.LegacyChatbox || mongoose.model('LegacyChatbox', schema);
