import mongoose from 'mongoose';

// Legacy MySQL table `cms_usersubmenu`, migrated as-is into collection_cms_usersubmenu.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    submenu_id: Number,
    user: String,
    status: Number,
    doneby: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_cms_usersubmenu' }
);

export const LegacyCmsUsersubmenu = mongoose.models.LegacyCmsUsersubmenu || mongoose.model('LegacyCmsUsersubmenu', schema);
