import mongoose from 'mongoose';

// Legacy MySQL table `agent_details`, migrated as-is into collection_agent_details.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Task For Documentation
//   - Invoice > Other Expenses
//   - Invoice > Vendor Invoice Followup
//   - Utilities > Flag Document
//   - Utilities > Hotel Request
//   - Utilities > PPE Request
//   - Vendor > Purchase Requisition

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    Agent_name: String,
    agent_shortname: String,
    Address: String,
    type: String,
    provider: String,
    purpose: String,
    prefix: String,
    contactperson: String,
    contactno: String,
    contactemail: String,
    contactemail2: String,
    services: String,
    consulate: String,
    nationality: String,
    tds_amount: String,
    gst_amount: String,
    bank_address: String,
    ifscode: String,
    bankname: String,
    accountname: String,
    accountno: String,
    panno: String,
    gstno: String,
    file: String,
    uppe_curr: String,
    uppe: Number,
    usafety_curr: String,
    usafety: Number,
    uhelmet_curr: String,
    uhelmet: Number,
    utorch_curr: String,
    utorch: Number,
    cpant_curr: String,
    cpant: Number,
    cshirt_curr: String,
    cshirt: Number,
    capron_curr: String,
    capron: Number,
    ccap_curr: String,
    ccap: Number,
    chairnet_curr: String,
    chairnet: Number,
    cshoes_curr: String,
    cshoes: Number,
    ppe_product: String,
    ppe_amount: String,
    remark: String,
    addedby: String,
    cdate: String,
    deactivate_date: String,
    deactivate_by: String,
    status: Number,
    approve: Number,
    phonecode: Number,
  },
  { strict: false, collection: 'collection_agent_details' }
);

export const LegacyAgentDetails = mongoose.models.LegacyAgentDetails || mongoose.model('LegacyAgentDetails', schema);
