import mongoose from 'mongoose';

// Legacy MySQL table `offcertificate`, migrated as-is into collection_offcertificate.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    certificate: String,
  },
  { strict: false, collection: 'collection_offcertificate' }
);

export const LegacyOffcertificate = mongoose.models.LegacyOffcertificate || mongoose.model('LegacyOffcertificate', schema);
