import mongoose from 'mongoose';

// Legacy MySQL table `cms_quotes`, migrated as-is into collection_cms_quotes.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    quote: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_cms_quotes' }
);

export const LegacyCmsQuotes = mongoose.models.LegacyCmsQuotes || mongoose.model('LegacyCmsQuotes', schema);
