import mongoose from 'mongoose';

// Legacy MySQL table `itr_doc`, migrated as-is into collection_itr_doc.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    itr_id: String,
    agreement_no: String,
    uplod: String,
    issue_date: String,
    valid_date: String,
    users: String,
    cdate: String,
    status: String,
  },
  { strict: false, collection: 'collection_itr_doc' }
);

export const LegacyItrDoc = mongoose.models.LegacyItrDoc || mongoose.model('LegacyItrDoc', schema);
