import mongoose from 'mongoose';

// Legacy MySQL table `tvacanciescandidate`, migrated as-is into collection_tvacanciescandidate.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > List of cancelled Joiners
//   - Documentation > Task For Documentation
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    pdate: String,
    vacancyid: String,
    addedby: String,
    mproposedto: String,
    mproposedby: String,
    assign_otp: String,
    assign_otp_valid: String,
    remark: String,
    cstatus: Number,
    aproveremark: String,
  },
  { strict: false, collection: 'collection_tvacanciescandidate' }
);

export const LegacyTvacanciescandidate = mongoose.models.LegacyTvacanciescandidate || mongoose.model('LegacyTvacanciescandidate', schema);
