import mongoose from 'mongoose';

// Legacy MySQL table `doctor`, migrated as-is into collection_doctor.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Vendor Invoice Followup
//   - Utilities > Medical Request

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    ddate: String,
    prefix: String,
    doctorname: String,
    email: String,
    email2: String,
    daddress: String,
    dphoneno: String,
    dphoneno2: String,
    remark: String,
    medical: String,
    amount: String,
    crew_amount: String,
    addby: String,
    adddate: String,
    editby: String,
    editdate: String,
    deactivate_date: String,
    deactivate_by: String,
    p_i: String,
    status: Number,
  },
  { strict: false, collection: 'collection_doctor' }
);

export const LegacyDoctor = mongoose.models.LegacyDoctor || mongoose.model('LegacyDoctor', schema);
