import mongoose from 'mongoose';

// Legacy MySQL table `prequisitionother`, migrated as-is into collection_prequisitionother.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    oid: Number,
    ostatus: Number,
    ocountry: String,
    oname: String,
    oindos: String,
    orank: String,
    odate: String,
    stage1: String,
    stage1d: String,
    stage2: String,
    stage2d: String,
    stage3: String,
    stage3d: String,
  },
  { strict: false, collection: 'collection_prequisitionother' }
);

export const LegacyPrequisitionother = mongoose.models.LegacyPrequisitionother || mongoose.model('LegacyPrequisitionother', schema);
