import mongoose from 'mongoose';

// Legacy MySQL table `shore_exp`, migrated as-is into collection_shore_exp.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    company: String,
    position: String,
    workfrom: String,
    workto: String,
    emailid: String,
    indosno: String,
  },
  { strict: false, collection: 'collection_shore_exp' }
);

export const LegacyShoreExp = mongoose.models.LegacyShoreExp || mongoose.model('LegacyShoreExp', schema);
