import mongoose from 'mongoose';

// Legacy MySQL table `nrpa`, migrated as-is into collection_nrpa.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - NRPA > Data Submit For eMigrate

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    nrpaid: Number,
    sapid: String,
    refno: String,
    name: String,
    nrpatype: String,
    joinertype: String,
    nationality: String,
    passport: String,
    ranktype: String,
    rank: Number,
    company: Number,
    vessle: Number,
    flag: String,
    imo: String,
    docs: String,
    uploads: String,
    contract_duration: String,
    date_leave: String,
    flight_date: String,
    signondate: String,
    signoffdate: String,
    date_ariveal: String,
    davailable: String,
    ticket: String,
    travellocation: String,
    remark: String,
    immigration_officer: String,
    director: String,
    select_po: String,
    po_numb: String,
    cdate: String,
    doneby: String,
    status: Number,
    approveby: String,
    cancelled_by: String,
    cancelled_remark: String,
    invoice: Number,
  },
  { strict: false, collection: 'collection_nrpa' }
);

export const LegacyNrpa = mongoose.models.LegacyNrpa || mongoose.model('LegacyNrpa', schema);
