import mongoose from 'mongoose';

// Legacy MySQL table `vvisa`, migrated as-is into collection_vvisa.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Vendor > Vendor Details

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    vid: Number,
    vcountry: String,
    vendorid: Number,
    vname: String,
    visa_type: String,
    vvisa: String,
    vamount: String,
    vrate: Number,
    till_date: String,
  },
  { strict: false, collection: 'collection_vvisa' }
);

export const LegacyVvisa = mongoose.models.LegacyVvisa || mongoose.model('LegacyVvisa', schema);
