import mongoose from 'mongoose';

// Legacy MySQL table `bmpl_assets`, migrated as-is into collection_bmpl_assets.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Utilities > Add Assets

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    asset: String,
    type: String,
    status: Number,
  },
  { strict: false, collection: 'collection_bmpl_assets' }
);

export const LegacyBmplAssets = mongoose.models.LegacyBmplAssets || mongoose.model('LegacyBmplAssets', schema);
