import mongoose from 'mongoose';

// Legacy MySQL table `reminder`, migrated as-is into collection_reminder.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    remindertext: String,
    reminderfor: String,
    reminderby: String,
    status: Number,
    checkstatus: Number,
    checkby: String,
    checktime: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_reminder' }
);

export const LegacyReminder = mongoose.models.LegacyReminder || mongoose.model('LegacyReminder', schema);
