import mongoose from 'mongoose';

// Legacy MySQL table `bmpl_ownership`, migrated as-is into collection_bmpl_ownership.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Ownership > List of BMPL Ownership

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    own_id: Number,
    owner_name: String,
    add_date: String,
    user: String,
    ownership_type: String,
    status: Number,
  },
  { strict: false, collection: 'collection_bmpl_ownership' }
);

export const LegacyBmplOwnership = mongoose.models.LegacyBmplOwnership || mongoose.model('LegacyBmplOwnership', schema);
