import mongoose from 'mongoose';

// Legacy MySQL table `dg_circular`, migrated as-is into collection_dg_circular.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > DG Circular 

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    agreement_no: String,
    uplod: String,
    issue_date: String,
    valid_date: String,
    summary: String,
    users: String,
    cdate: String,
    status: String,
  },
  { strict: false, collection: 'collection_dg_circular' }
);

export const LegacyDgCircular = mongoose.models.LegacyDgCircular || mongoose.model('LegacyDgCircular', schema);
