import mongoose from 'mongoose';

// Legacy MySQL table `staff_attendance`, migrated as-is into collection_staff_attendance.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Dailyattendance report
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    in_time: String,
    out_time: String,
    day_type: String,
    leave_time: String,
    intime_location: String,
    intime_location_status: String,
    outtime_location: String,
    outtime_location_status: String,
    date: String,
    remarks: String,
    userid: Number,
    username: String,
    status: Number,
  },
  { strict: false, collection: 'collection_staff_attendance' }
);

export const LegacyStaffAttendance = mongoose.models.LegacyStaffAttendance || mongoose.model('LegacyStaffAttendance', schema);
