import mongoose from 'mongoose';

// Legacy MySQL table `cranetype`, migrated as-is into collection_cranetype.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    crane_type: String,
    status: Number,
  },
  { strict: false, collection: 'collection_cranetype' }
);

export const LegacyCranetype = mongoose.models.LegacyCranetype || mongoose.model('LegacyCranetype', schema);
