import mongoose from 'mongoose';

// Legacy MySQL table `payroll`, migrated as-is into collection_payroll.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Pay Roll Management
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    userid: Number,
    basic: Number,
    hra: Number,
    pf: Number,
    epf: Number,
    bonus: Number,
    pro_fun: Number,
    p_tax: Number,
    emp_esic: Number,
    esic: Number,
    gross_salary: Number,
    conveyance: Number,
    eesic: Number,
    paysal: String,
    advanceloan: Number,
    arrears: Number,
    salcut: Number,
    tds: Number,
    noofwdays: String,
    noofhdays: Number,
    formonth: String,
    noofabsent: Number,
    puser: String,
    pdate: String,
    status: Number,
    given_status: String,
    approval: Number,
    staff_remarks: String,
    confirm: Number,
    confirm_date: String,
    dashboard: Number,
    special_allowance: Number,
    emp_profun: Number,
    total_gross: Number,
    bank_name: String,
    pre_d: Number,
    absen_day: Number,
  },
  { strict: false, collection: 'collection_payroll' }
);

export const LegacyPayroll = mongoose.models.LegacyPayroll || mongoose.model('LegacyPayroll', schema);
