import mongoose from 'mongoose';

// Legacy MySQL table `vesseltype`, migrated as-is into collection_vesseltype.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Sourcing > View Candidate CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    vesselid: Number,
    vesseltype: String,
    shipid: String,
    status: String,
    rankid: Number,
  },
  { strict: false, collection: 'collection_vesseltype' }
);

export const LegacyVesseltype = mongoose.models.LegacyVesseltype || mongoose.model('LegacyVesseltype', schema);
