import mongoose from 'mongoose';

// Legacy MySQL table `medical_request`, migrated as-is into collection_medical_request.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Task For Documentation
//   - Utilities > Medical Request

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    mid: Number,
    indosno: String,
    email: String,
    vendor: Number,
    company: Number,
    screen_ss: String,
    vesselname: String,
    jobid: Number,
    medical: String,
    paymentby: String,
    paidto_vendor: String,
    paidto_bmpl: String,
    directto_vendor: Number,
    amount: String,
    rate: String,
    cdate: String,
    doe: String,
    addby: String,
    status: Number,
    vendorinvoice_followup: Number,
  },
  { strict: false, collection: 'collection_medical_request' }
);

export const LegacyMedicalRequest = mongoose.models.LegacyMedicalRequest || mongoose.model('LegacyMedicalRequest', schema);
