import mongoose from 'mongoose';

// Legacy MySQL table `mmd`, migrated as-is into collection_mmd.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Immunization Card
//   - DG > MMD
//   - Invoice > Nedpass Invoice

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    type: String,
    mmd: String,
    authority: String,
    branch_name: String,
    branch_address: String,
    status: Number,
    cdate: String,
  },
  { strict: false, collection: 'collection_mmd' }
);

export const LegacyMmd = mongoose.models.LegacyMmd || mongoose.model('LegacyMmd', schema);
