import mongoose from 'mongoose';

// Legacy MySQL table `dailyaccesslimit`, migrated as-is into collection_dailyaccesslimit.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Utilities > Flag Document
//   - Utilities > Medical Request

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    userid: String,
    fromdate: String,
    todate: String,
    flag_fromdate: String,
    flag_todate: String,
    medical_fromdate: String,
    medical_todate: String,
    visa_fromdate: String,
    visa_todate: String,
    doe: String,
    status: Number,
  },
  { strict: false, collection: 'collection_dailyaccesslimit' }
);

export const LegacyDailyaccesslimit = mongoose.models.LegacyDailyaccesslimit || mongoose.model('LegacyDailyaccesslimit', schema);
