import mongoose from 'mongoose';

// Legacy MySQL table `basic_requirement`, migrated as-is into collection_basic_requirement.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    companyid: Number,
    question: String,
    requirement: String,
    rank: Number,
    type: String,
    status: Number,
  },
  { strict: false, collection: 'collection_basic_requirement' }
);

export const LegacyBasicRequirement = mongoose.models.LegacyBasicRequirement || mongoose.model('LegacyBasicRequirement', schema);
