import mongoose from 'mongoose';

// Legacy MySQL table `nedpass_rate`, migrated as-is into collection_nedpass_rate.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Nedpass Invoice
//   - Utilities > Ned Pass

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    type_pass: String,
    particulars: String,
    new_ext: String,
    material: String,
    rates: String,
    status: Number,
    addedby: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_nedpass_rate' }
);

export const LegacyNedpassRate = mongoose.models.LegacyNedpassRate || mongoose.model('LegacyNedpassRate', schema);
