import mongoose from 'mongoose';

// Legacy MySQL table `email_format`, migrated as-is into collection_email_format.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - Report > Candidate Information
//   - Utilities > Email Format

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    addedby: String,
    cdate: mongoose.Schema.Types.Mixed,
    content: String,
    email_format: String,
    header: String,
    id: { type: Number, index: true },
    screenshot: String,
    status: Number,
  },
  { strict: false, collection: 'collection_email_format' }
);

export const LegacyEmailFormat = mongoose.models.LegacyEmailFormat || mongoose.model('LegacyEmailFormat', schema);
