import mongoose from 'mongoose';

// Legacy MySQL table `nedpass_invoice`, migrated as-is into collection_nedpass_invoice.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Nedpass Invoice

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    inv_no: String,
    po_number: String,
    ned_id: String,
    bankid: Number,
    inv_date: String,
    cdate: String,
    doneby: String,
  },
  { strict: false, collection: 'collection_nedpass_invoice' }
);

export const LegacyNedpassInvoice = mongoose.models.LegacyNedpassInvoice || mongoose.model('LegacyNedpassInvoice', schema);
