import mongoose from 'mongoose';

// Legacy MySQL table `rpsl_agencies`, migrated as-is into collection_rpsl_agencies.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Report > Crew Welfare-GOVT Report

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    rpsl_name: String,
    shortname: String,
    address: String,
    email: String,
    mobile: String,
    stamp: String,
    website: String,
    status: Number,
  },
  { strict: false, collection: 'collection_rpsl_agencies' }
);

export const LegacyRpslAgencies = mongoose.models.LegacyRpslAgencies || mongoose.model('LegacyRpslAgencies', schema);
