import mongoose from 'mongoose';

// Legacy MySQL table `ownership_vessel`, migrated as-is into collection_ownership_vessel.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Ownership > List of BMPL Ownership

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    company: String,
    doc_name: String,
    document: String,
    issue_date: String,
    validity_date: String,
    addedby: String,
    doc_id: Number,
    own_id: Number,
    status: Number,
  },
  { strict: false, collection: 'collection_ownership_vessel' }
);

export const LegacyOwnershipVessel = mongoose.models.LegacyOwnershipVessel || mongoose.model('LegacyOwnershipVessel', schema);
