import mongoose from 'mongoose';

// Legacy MySQL table `cms_actions`, migrated as-is into collection_cms_actions.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    submenu_id: Number,
    action_name: String,
    status: Number,
  },
  { strict: false, collection: 'collection_cms_actions' }
);

export const LegacyCmsActions = mongoose.models.LegacyCmsActions || mongoose.model('LegacyCmsActions', schema);
