import mongoose from 'mongoose';

// Legacy MySQL table `invoice_pdf`, migrated as-is into collection_invoice_pdf.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Print Invoice

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    invid: String,
    inv_doc: String,
    added_time: String,
    addedby: String,
    remark: String,
    invoic_no: String,
    num: Number,
  },
  { strict: false, collection: 'collection_invoice_pdf' }
);

export const LegacyInvoicePdf = mongoose.models.LegacyInvoicePdf || mongoose.model('LegacyInvoicePdf', schema);
