import mongoose from 'mongoose';

// Legacy MySQL table `ksa_visa`, migrated as-is into collection_ksa_visa.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Sea Service correction
//   - Documentation > Task For Documentation
//   - Utilities > In/Out Documents

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    ksa_id: Number,
    visa_no: String,
    vendor_amount: String,
    rate: String,
    name: String,
    indosno: String,
    passportno: String,
    company_name: String,
    rank: String,
    visa_rank: String,
    consulate: String,
    cover_letter: String,
    dept: String,
    letter_copy: String,
    kvisa_amount: String,
    visa_category: String,
    visa_type: String,
    passport_issuedate: String,
    passport_expdate: String,
    proceed_country: String,
    immigration: String,
    proceed_city: String,
    commencing_from: String,
    commencing_to: String,
    created_by: String,
    appointment: String,
    dob: String,
    doe: String,
    loireceiveddate: String,
    agentsentdate: String,
    paidstatus: String,
    canpaidstatus: String,
    txt_director: String,
    txt_staff: Number,
    txt_vagent: Number,
    companyid: Number,
    vesselname: String,
    jobid: String,
    vessel: String,
    loidoe: String,
    loiuser: String,
    statusin: String,
    statusd: String,
    visa_issuance: String,
    visa_expiry: String,
    approval: Number,
    approveby: String,
    paidby: String,
    paytobmpl: String,
    directto_vendor: Number,
    paidamount: String,
    paidcanamount: String,
    additional_amount: String,
    crewpaysrcn: String,
    loi: String,
    issue_status: String,
    comp_inv: Number,
    receipt_approval: Number,
    receipt_print: Number,
    emailsent: Number,
    cancel_remark: String,
    cancel_by: String,
    cancel_date: String,
    status: Number,
    vendorinvoice_followup: Number,
  },
  { strict: false, collection: 'collection_ksa_visa' }
);

export const LegacyKsaVisa = mongoose.models.LegacyKsaVisa || mongoose.model('LegacyKsaVisa', schema);
