import mongoose from 'mongoose';

// Legacy MySQL table `certificate`, migrated as-is into collection_certificate.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    certificate: String,
  },
  { strict: false, collection: 'collection_certificate' }
);

export const LegacyCertificate = mongoose.models.LegacyCertificate || mongoose.model('LegacyCertificate', schema);
