import mongoose from 'mongoose';

// Legacy MySQL table `grievance_chat`, migrated as-is into collection_grievance_chat.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Sea Service correction

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    g_id: Number,
    emailid: String,
    indosno: String,
    chat: String,
    cdate: String,
    user: String,
    status: Number,
  },
  { strict: false, collection: 'collection_grievance_chat' }
);

export const LegacyGrievanceChat = mongoose.models.LegacyGrievanceChat || mongoose.model('LegacyGrievanceChat', schema);
