import mongoose from 'mongoose';

// Legacy MySQL table `newasset_table`, migrated as-is into collection_newasset_table.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Staff Member List
//   - Utilities > Add Assets

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    asset_user: String,
    asset_name: String,
    asset_key: String,
    asset_details: String,
    date: String,
    status: String,
    remark: String,
  },
  { strict: false, collection: 'collection_newasset_table' }
);

export const LegacyNewassetTable = mongoose.models.LegacyNewassetTable || mongoose.model('LegacyNewassetTable', schema);
