import mongoose from 'mongoose';

// Legacy MySQL table `blacklist`, migrated as-is into collection_blacklist.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Task For Documentation
//   - Report > Back Out Candidate

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    blacklist_id: Number,
    indosno: String,
    companyname: String,
    vesselname: String,
    brank: String,
    remark: String,
    vacancyid: Number,
    nature: String,
    immediate_cause: String,
    intermediate_cause: String,
    root_cause: String,
    actiontaken: String,
    baddedby: String,
    bdate: String,
    status: Number,
    cdate: String,
    doneby: String,
  },
  { strict: false, collection: 'collection_blacklist' }
);

export const LegacyBlacklist = mongoose.models.LegacyBlacklist || mongoose.model('LegacyBlacklist', schema);
