import mongoose from 'mongoose';

// Legacy MySQL table `invoice_vendor`, migrated as-is into collection_invoice_vendor.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    invoice: String,
    inv_count: Number,
    refno: String,
    invoice_company: Number,
    items: String,
    vendor: Number,
    increment: Number,
    fromdate: String,
    todate: String,
    doneby: String,
    cdate: String,
    status: Number,
  },
  { strict: false, collection: 'collection_invoice_vendor' }
);

export const LegacyInvoiceVendor = mongoose.models.LegacyInvoiceVendor || mongoose.model('LegacyInvoiceVendor', schema);
