import mongoose from 'mongoose';

// Legacy MySQL table `taskassign`, migrated as-is into collection_taskassign.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > My License
//   - Home > Dashboard
//   - Sourcing > List of vacancies
//   - Sourcing > Task For Sourcing

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    eid: Number,
    vacn_id: String,
    dov: String,
    rankname: String,
    user: String,
    image: String,
    assignby: String,
    assignto: String,
    sassign: String,
    ackn: Number,
    ackndate: String,
  },
  { strict: false, collection: 'collection_taskassign' }
);

export const LegacyTaskassign = mongoose.models.LegacyTaskassign || mongoose.model('LegacyTaskassign', schema);
