import mongoose from 'mongoose';

// Legacy MySQL table `rank`, migrated as-is into collection_rank.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > List of cancelled Joiners
//   - Documentation > Task For Documentation
//   - Home > Dashboard
//   - Invoice > Nedpass Invoice
//   - Invoice > Proforma Invoice
//   - NRPA > Other Nationality Crew
//   - Owner > List of Owner
//   - Report > All Report
//   - Report > Back Out Candidate
//   - Report > Signoff Data Reports
//   - Sourcing > Candidate Proposal Status
//   - Sourcing > List of vacancies
//   - Sourcing > Seafarer
//   - Sourcing > Task For Sourcing
//   - Sourcing > View Candidate CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    rankid: Number,
    Type: String,
    rank: String,
    status: String,
  },
  { strict: false, collection: 'collection_rank' }
);

export const LegacyRank = mongoose.models.LegacyRank || mongoose.model('LegacyRank', schema);
