import mongoose from 'mongoose';

// Legacy MySQL table `important_information`, migrated as-is into collection_important_information.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Owner > List of Owner

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    uplod: String,
    user: String,
    cdate: String,
    comid: Number,
    status: Number,
  },
  { strict: false, collection: 'collection_important_information' }
);

export const LegacyImportantInformation = mongoose.models.LegacyImportantInformation || mongoose.model('LegacyImportantInformation', schema);
