import mongoose from 'mongoose';

// Legacy MySQL table `cms_menu`, migrated as-is into collection_cms_menu.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    menu_id: Number,
    menu_name: String,
    status: Number,
  },
  { strict: false, collection: 'collection_cms_menu' }
);

export const LegacyCmsMenu = mongoose.models.LegacyCmsMenu || mongoose.model('LegacyCmsMenu', schema);
