import mongoose from 'mongoose';

// Legacy MySQL table `inandout_documents`, migrated as-is into collection_inandout_documents.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - Utilities > In/Out Documents

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    document_id: Number,
    document_type: String,
    document_by: String,
    instructed_by: String,
    otpemail: String,
    other_person_name: String,
    other_person_cred: String,
    other_person_contact: String,
    credential: String,
    fullname: String,
    rank: String,
    emailid: String,
    passport: String,
    document_category: String,
    category_id: Number,
    doc_name: String,
    doc_quantity: Number,
    device_id: String,
    device_vendor: String,
    remark: String,
    document_status: String,
    location: String,
    otp: Number,
    verify: Number,
    verifyby: String,
    dispatched_doc_sea_service_id: String,
    added_by: String,
    added_date: String,
    status: Number,
  },
  { strict: false, collection: 'collection_inandout_documents' }
);

export const LegacyInandoutDocuments = mongoose.models.LegacyInandoutDocuments || mongoose.model('LegacyInandoutDocuments', schema);
