import mongoose from 'mongoose';

// Legacy MySQL table `editcompanylogin`, migrated as-is into collection_editcompanylogin.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Staff Member List

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    eid: Number,
    id: { type: Number, index: true },
    prefix: String,
    fullname: String,
    phonenumber: Number,
    username: String,
    dob: String,
    password: String,
    lastchange_pass: String,
    aadhar: String,
    pancard: String,
    panno: String,
    aadharno: String,
    cp_number: String,
    cp_dateofissue: String,
    vaccine_certi: String,
    fisrtdose: String,
    seconddose: String,
    laptop_sn: String,
    laptop_imei: String,
    avidate: String,
    msoffice365: String,
    lastdate: String,
    email: String,
    dept: String,
    sourcing_rank: String,
    doc_company: String,
    staff_id: String,
    image: String,
    status: String,
    gstatus: String,
    address: String,
    position: String,
    salary: Number,
    company: String,
    joining_date: String,
    leaving_date: String,
    addedby: String,
    addedon: String,
    loggedin: String,
    loggedoff: String,
    checklog: String,
    ipaddress: String,
    city: String,
    region: String,
    country: String,
    loc: String,
    blockstatus: String,
    approval: Number,
    remark: String,
    dailyaccess: Number,
    request: Number,
    request_time: String,
    salaryfrom: String,
    salaryto: String,
  },
  { strict: false, collection: 'collection_editcompanylogin' }
);

export const LegacyEditcompanylogin = mongoose.models.LegacyEditcompanylogin || mongoose.model('LegacyEditcompanylogin', schema);
