import mongoose from 'mongoose';

// Legacy MySQL table `tbl_events`, migrated as-is into collection_tbl_events.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Accounting Calendar

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    title: String,
    start: String,
    end: String,
  },
  { strict: false, collection: 'collection_tbl_events' }
);

export const LegacyTblEvents = mongoose.models.LegacyTblEvents || mongoose.model('LegacyTblEvents', schema);
