import mongoose from 'mongoose';

// Legacy MySQL table `pcc`, migrated as-is into collection_pcc.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Letter Details > PCC Manager

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    cname: String,
    fname: String,
    dob: String,
    indosno: String,
    address1: String,
    address2: String,
    addby: String,
    adddate: String,
    editby: String,
    editdate: String,
    date: String,
    refno: String,
    pccno: Number,
    owner: String,
    profile: String,
    field: String,
    pass: String,
    doi: String,
    doe: String,
    lname: String,
    director: String,
    approval: Number,
    approveby: String,
    requested_by: String,
    issue_status: String,
  },
  { strict: false, collection: 'collection_pcc' }
);

export const LegacyPcc = mongoose.models.LegacyPcc || mongoose.model('LegacyPcc', schema);
