import mongoose from 'mongoose';

// Legacy MySQL table `bo_rank`, migrated as-is into collection_bo_rank.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    rankname: String,
    post: Number,
    type: String,
    subcategory: String,
    ranksearch: String,
    catagory: String,
    doe: String,
    status: Number,
  },
  { strict: false, collection: 'collection_bo_rank' }
);

export const LegacyBoRank = mongoose.models.LegacyBoRank || mongoose.model('LegacyBoRank', schema);
