import mongoose from 'mongoose';

// Legacy MySQL table `countries`, migrated as-is into collection_countries.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Sourcing > View Candidate CV

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    sortname: String,
    country: String,
    phonecode: Number,
  },
  { strict: false, collection: 'collection_countries' }
);

export const LegacyCountries = mongoose.models.LegacyCountries || mongoose.model('LegacyCountries', schema);
