import mongoose from 'mongoose';

// Legacy MySQL table `vhotel`, migrated as-is into collection_vhotel.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > Task For Documentation

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    hid: Number,
    thotel: String,
    vhotel: String,
    hdescription: String,
    hcurrency: String,
    hfee: Number,
    vfee: Number,
  },
  { strict: false, collection: 'collection_vhotel' }
);

export const LegacyVhotel = mongoose.models.LegacyVhotel || mongoose.model('LegacyVhotel', schema);
