import mongoose from 'mongoose';

// Legacy MySQL table `coc_country`, migrated as-is into collection_coc_country.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    coc_country: String,
  },
  { strict: false, collection: 'collection_coc_country' }
);

export const LegacyCocCountry = mongoose.models.LegacyCocCountry || mongoose.model('LegacyCocCountry', schema);
