import mongoose from 'mongoose';

// Legacy MySQL table `bmpl_assets_staff`, migrated as-is into collection_bmpl_assets_staff.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Staff Member List

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    username: String,
    asset_name: String,
    asset_id: String,
    asset_details: String,
    asset_quantity: Number,
    remark: String,
    status: Number,
  },
  { strict: false, collection: 'collection_bmpl_assets_staff' }
);

export const LegacyBmplAssetsStaff = mongoose.models.LegacyBmplAssetsStaff || mongoose.model('LegacyBmplAssetsStaff', schema);
