import mongoose from 'mongoose';

// Legacy MySQL table `vessel_edit`, migrated as-is into collection_vessel_edit.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Owner > List of Owner

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    vessel_id: Number,
    vesselname: String,
    company_name: String,
    IMO_Number: String,
    vessel_code: String,
    vessel_category: String,
    vesseltype: String,
    grt: Number,
    bhp: Number,
    Flag: String,
    cdagreement: String,
    seagreement: String,
    pipolicynumber: String,
    policydateofv: String,
    pipolicydocument: String,
    mlccertificateno: String,
    dofmlccertificate: String,
    doexpiry: String,
    maritimelabourconvention: String,
    fsdnumber: String,
    fsdvalidity: String,
    fsdocument: String,
    dmlcp1: String,
    dmlc2: String,
    status: String,
    remark: String,
    doneby: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_vessel_edit' }
);

export const LegacyVesselEdit = mongoose.models.LegacyVesselEdit || mongoose.model('LegacyVesselEdit', schema);
