import mongoose from 'mongoose';

// Legacy MySQL table `company`, migrated as-is into collection_company.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - Documentation > List of cancelled Joiners
//   - Documentation > Pooled Crew
//   - Documentation > Task For Documentation
//   - Documentation > Travel Diary
//   - Home > Dashboard
//   - Invoice > Company Invoice Followup
//   - Invoice > Print Invoice
//   - Invoice > Proforma Invoice
//   - Report > Back Out Candidate
//   - Report > Candidate Information
//   - Report > Crew Welfare-GOVT Report
//   - Report > Signoff Data Reports
//   - Shore Job > Add Shore Vacancy
//   - Sourcing > Candidate Proposal Status
//   - Sourcing > List of vacancies
//   - Sourcing > Task For Sourcing
//   - Utilities > Flag Document
//   - Utilities > Medical Request
//   - Utilities > PPE Request

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    company_id: Number,
    companyname: String,
    status: String,
  },
  { strict: false, collection: 'collection_company' }
);

export const LegacyCompany = mongoose.models.LegacyCompany || mongoose.model('LegacyCompany', schema);
