import mongoose from 'mongoose';

// Legacy MySQL table `payments`, migrated as-is into collection_payments.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    indosno: String,
    emailid: String,
    fullname: String,
    category: String,
    category_id: String,
    payment_method: String,
    payment_to_type: String,
    payment_to: String,
    payment_proof: String,
    payment_amount: String,
    payment_status: String,
    payment_date: String,
    add_date: String,
    remark: String,
    add_by: String,
  },
  { strict: false, collection: 'collection_payments' }
);

export const LegacyPayments = mongoose.models.LegacyPayments || mongoose.model('LegacyPayments', schema);
