import mongoose from 'mongoose';

// Legacy MySQL table `supadmin`, migrated as-is into collection_supadmin.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Dailyattendance report
//   - BMPL Employee > Staff Member List
//   - BMPL Ownership > List of BMPL Ownership
//   - DG > DG Circular 
//   - DG > DG Related Icon
//   - DG > Immunization Card
//   - DG > Issuance of Sea-Service
//   - DG > Sea Service correction
//   - DG > Verification Of TAR Book
//   - Documentation > Document Upload
//   - Documentation > List of cancelled Joiners
//   - Documentation > Pooled Crew
//   - Documentation > Rejoining Vacancies
//   - Documentation > Task For Documentation
//   - Home > Dashboard
//   - Invoice > Print Invoice
//   - Letter Details > Old Sea Service
//   - Owner > List of Owner
//   - Report > Candidate Information
//   - Shore Job > Add Shore Vacancy
//   - Sourcing > Candidate Proposal Status
//   - Sourcing > Deleted/Closed Vacancies
//   - Sourcing > List of vacancies
//   - Sourcing > Seafarer
//   - Sourcing > Task For Sourcing
//   - Sourcing > View Candidate CV
//   - Utilities > Flag Document
//   - Utilities > Medical Request
//   - Utilities > Ned Pass
//   - Utilities > PPE Request
//   - Vendor > Purchase Requisition

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    name: String,
  },
  { strict: false, collection: 'collection_supadmin' }
);

export const LegacySupadmin = mongoose.models.LegacySupadmin || mongoose.model('LegacySupadmin', schema);
