import mongoose from 'mongoose';

// Legacy MySQL table `priocheckname`, migrated as-is into collection_priocheckname.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    priorole: String,
    userid: Number,
    username: String,
  },
  { strict: false, collection: 'collection_priocheckname' }
);

export const LegacyPriocheckname = mongoose.models.LegacyPriocheckname || mongoose.model('LegacyPriocheckname', schema);
