import mongoose from 'mongoose';

// Legacy MySQL table `ccoscertificate`, migrated as-is into collection_ccoscertificate.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Letter Details > Old Sea Service

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    cos_refno: String,
    cosrno: Number,
    cos_candname: String,
    cos_rank: String,
    cos_passport: String,
    cos_indos: String,
    cos_date: String,
    cos_cdc: String,
    cos_owner: String,
    cos_vessel: String,
    flag: String,
    cos_fleettype: String,
    cos_shiptype: String,
    cos_fromdate: String,
    cos_todate: String,
    cos_grt: String,
    cos_nrt: String,
    cos_kwt: String,
    conduct: String,
    ability: String,
    sobriety: String,
    addby: String,
    adddate: String,
    editby: String,
    editdate: String,
    status: String,
    email: String,
    remark: String,
    voyage: String,
    imo: String,
    address: String,
    address1: String,
    address2: String,
    address3: String,
    director: String,
    cv_id: Number,
    lines2: String,
    lines1: String,
    cos_status: String,
    cos_auser: String,
    cos_user: String,
    cos_print: String,
    print_date: String,
  },
  { strict: false, collection: 'collection_ccoscertificate' }
);

export const LegacyCcoscertificate = mongoose.models.LegacyCcoscertificate || mongoose.model('LegacyCcoscertificate', schema);
