import mongoose from 'mongoose';

// Legacy MySQL table `cranemaker`, migrated as-is into collection_cranemaker.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    crane_maker: String,
    status: Number,
  },
  { strict: false, collection: 'collection_cranemaker' }
);

export const LegacyCranemaker = mongoose.models.LegacyCranemaker || mongoose.model('LegacyCranemaker', schema);
