import mongoose from 'mongoose';

// Legacy MySQL table `expiry_tbl`, migrated as-is into collection_expiry_tbl.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Utilities > Expiry Plans

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    plan_details: String,
    company_name: String,
    email_id: String,
    user_name: String,
    password: String,
    plans: String,
    plan_price: String,
    plan_by_date: String,
    plan_by_expiry: String,
    Status: String,
    Action: String,
  },
  { strict: false, collection: 'collection_expiry_tbl' }
);

export const LegacyExpiryTbl = mongoose.models.LegacyExpiryTbl || mongoose.model('LegacyExpiryTbl', schema);
