import mongoose from 'mongoose';

// Legacy MySQL table `sea_service_request`, migrated as-is into collection_sea_service_request.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    contractid: String,
    indosno: String,
    emailid: String,
    cdate: String,
    status: Number,
    issue_status: Number,
    assigned_to: String,
  },
  { strict: false, collection: 'collection_sea_service_request' }
);

export const LegacySeaServiceRequest = mongoose.models.LegacySeaServiceRequest || mongoose.model('LegacySeaServiceRequest', schema);
