import mongoose from 'mongoose';

// Legacy MySQL table `company_tariff`, migrated as-is into collection_company_tariff.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Utilities > Flag Document

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    added_by: String,
    added_date: mongoose.Schema.Types.Mixed,
    amount: Number,
    category: String,
    companyid: Number,
    currency: String,
    id: { type: Number, index: true },
    product: String,
    product_type: String,
    status: Number,
  },
  { strict: false, collection: 'collection_company_tariff' }
);

export const LegacyCompanyTariff = mongoose.models.LegacyCompanyTariff || mongoose.model('LegacyCompanyTariff', schema);
