import mongoose from 'mongoose';

// Legacy MySQL table `impweblink`, migrated as-is into collection_impweblink.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    title: String,
    link: String,
    user: String,
    email: String,
    password: String,
    date: String,
    type: String,
  },
  { strict: false, collection: 'collection_impweblink' }
);

export const LegacyImpweblink = mongoose.models.LegacyImpweblink || mongoose.model('LegacyImpweblink', schema);
