import mongoose from 'mongoose';

// Legacy MySQL table `presea`, migrated as-is into collection_presea.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    presea_name: String,
    status: Number,
  },
  { strict: false, collection: 'collection_presea' }
);

export const LegacyPresea = mongoose.models.LegacyPresea || mongoose.model('LegacyPresea', schema);
