import mongoose from 'mongoose';

// Legacy MySQL table `companylogin`, migrated as-is into collection_companylogin.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - BMPL Employee > Dailyattendance report
//   - BMPL Employee > Pay Roll Management
//   - BMPL Employee > Staff Member List
//   - Documentation > List of cancelled Joiners
//   - Documentation > Task For Documentation
//   - Home > Dashboard
//   - Report > Back Out Candidate
//   - Report > Candidate Information
//   - Sourcing > Candidate Proposal Status
//   - Sourcing > List of vacancies
//   - Sourcing > Seafarer
//   - Sourcing > Task For Sourcing
//   - Utilities > CMS Control Panel

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    prefix: String,
    fullname: String,
    status: String,
    per_phone: Number,
    phonenumber: Number,
    username: String,
    dob: String,
    password: String,
    lastchange_pass: String,
    aadhar: String,
    pancard: String,
    cv: String,
    sign: String,
    panno: String,
    aadharno: String,
    cp_number: String,
    cp_dateofissue: String,
    vaccine_certi: String,
    fisrtdose: String,
    seconddose: String,
    thirddose: String,
    laptop_sn: String,
    laptop_imei: String,
    avidate: String,
    msoffice365: String,
    lastdate: String,
    per_email: String,
    email: String,
    dept: String,
    sourcing_rank: String,
    doc_company: String,
    staff_id: String,
    image: String,
    gstatus: String,
    address: String,
    position: String,
    uin_no: String,
    salary: Number,
    company: String,
    joining_date: String,
    leaving_date: String,
    addedby: String,
    addedon: String,
    loggedin: String,
    loggedoff: String,
    checklog: String,
    ipaddress: String,
    city: String,
    region: String,
    country: String,
    loc: String,
    blockstatus: String,
    approval: Number,
    bank_name: String,
    bank_account_number: Number,
    account_holder_name: String,
    ifsc_code: String,
    monthly_target: Number,
    remark: String,
    dailyaccess: Number,
    request: Number,
    request_time: String,
    salaryfrom: String,
    salaryto: String,
    cookies: String,
    wati_otp: Number,
    promotion_date: String,
    last_proposal_date: String,
    offerletter: Number,
    location: String,
    jd: String,
    handoverto: Number,
    sourcing_rank_multiple: String,
  },
  { strict: false, collection: 'collection_companylogin' }
);

export const LegacyCompanylogin = mongoose.models.LegacyCompanylogin || mongoose.model('LegacyCompanylogin', schema);
