import mongoose from 'mongoose';

// Legacy MySQL table `handover_details`, migrated as-is into collection_handover_details.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - DG > Issuance of Sea-Service
//   - Utilities > In/Out Documents

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    handovertype: String,
    credential: String,
    vendor: String,
    courier_to: String,
    courier_by: String,
    vendor_name: String,
    charges: String,
    trackid: String,
    cnumber: String,
    emailid: String,
    fullname: String,
    crewadd: String,
    dispadd: String,
    doc_name: String,
    doc_refno: String,
    handoverby: String,
    handoverdate: String,
    remarks: String,
    personname: String,
    personphone: String,
    personemailid: String,
    otp: String,
    verify: Number,
    verifyby: String,
    courier_charges: String,
    addby: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_handover_details' }
);

export const LegacyHandoverDetails = mongoose.models.LegacyHandoverDetails || mongoose.model('LegacyHandoverDetails', schema);
