import mongoose from 'mongoose';

// Legacy MySQL table `education_type`, migrated as-is into collection_education_type.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    edu_type: String,
    status: Number,
  },
  { strict: false, collection: 'collection_education_type' }
);

export const LegacyEducationType = mongoose.models.LegacyEducationType || mongoose.model('LegacyEducationType', schema);
