import mongoose from 'mongoose';

// Legacy MySQL table `cms_usermenu`, migrated as-is into collection_cms_usermenu.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    menu_id: Number,
    user: String,
    status: Number,
    doneby: String,
    cdate: String,
  },
  { strict: false, collection: 'collection_cms_usermenu' }
);

export const LegacyCmsUsermenu = mongoose.models.LegacyCmsUsermenu || mongoose.model('LegacyCmsUsermenu', schema);
