import mongoose from 'mongoose';

// Legacy MySQL table `emp_request`, migrated as-is into collection_emp_request.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Home > Dashboard
//   - Utilities > Add Assets

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    subject: String,
    content: String,
    req_by: String,
    approval: String,
    date: String,
    ticket: String,
    fromdate: String,
    todate: String,
    address: String,
    position: String,
    dept: String,
    phonenumber: String,
    reason: String,
    requestDate: String,
    selectedAsset: String,
    yearly_paid_leave: String,
    used_leave: String,
    remaining_leave: String,
    unpaid_leave: String,
    thismonth_paid_leave: String,
    calculated_paid_leave: String,
    monthname: String,
  },
  { strict: false, collection: 'collection_emp_request' }
);

export const LegacyEmpRequest = mongoose.models.LegacyEmpRequest || mongoose.model('LegacyEmpRequest', schema);
