import mongoose from 'mongoose';

// Legacy MySQL table `bbdevelopment`, migrated as-is into collection_bbdevelopment.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Utilities > GlobalSH

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    bid: Number,
    company_name: String,
    contact_number: String,
    location: String,
    emailid: String,
    bcategory: String,
    remark: String,
    bdate: String,
    buser: String,
    ebid: Number,
    bstatus: Number,
    beditdate: String,
    bedituser: String,
  },
  { strict: false, collection: 'collection_bbdevelopment' }
);

export const LegacyBbdevelopment = mongoose.models.LegacyBbdevelopment || mongoose.model('LegacyBbdevelopment', schema);
