import mongoose from 'mongoose';

// Legacy MySQL table `nedpass`, migrated as-is into collection_nedpass.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Invoice > Nedpass Invoice
//   - Utilities > Ned Pass

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    id: { type: Number, index: true },
    prefix: String,
    nationality: String,
    indosno: String,
    phoneno: String,
    country: String,
    state: String,
    city: String,
    crewname: String,
    txt_email: String,
    txt_offname: Number,
    txt_vess: String,
    txt_vesscode: String,
    txt_rank: String,
    txt_passport: String,
    txt_passtype: String,
    priority: String,
    txt_nedpassno: String,
    txt_billnumber: String,
    txt_billdate: String,
    txt_nedtype: String,
    particulars: Number,
    txt_cgst: Number,
    txt_sgst: Number,
    txt_igst: Number,
    txt_tgst: Number,
    txt_gstl: Number,
    txt_description: String,
    proposal_date1: String,
    file1: String,
    txt_Remark1: String,
    proposal_date2: String,
    file2: String,
    txt_Remark2: String,
    proposal_date3: String,
    file3: String,
    txt_Remark3: String,
    proposal_date4: String,
    file4: String,
    txt_Remark4: String,
    proposal_date5: String,
    pass_expdate: String,
    file5: String,
    file6: String,
    amount: String,
    txt_Remark5: String,
    addedby: String,
    coveringletter: String,
    cancelrequest: Number,
    remarks: String,
    cancelby: String,
    status: Number,
    cdate: String,
  },
  { strict: false, collection: 'collection_nedpass' }
);

export const LegacyNedpass = mongoose.models.LegacyNedpass || mongoose.model('LegacyNedpass', schema);
