import mongoose from 'mongoose';

// Legacy MySQL table `vessel`, migrated as-is into collection_vessel.
// Generated by scripts/generateLegacyModels.mjs from the migrated data;
// types reflect what the rows actually hold (Mixed = both text and numbers
// occur). Edit freely - the generator never overwrites an existing file.
//
// Used by legacy admin pages:
//   - Documentation > List of cancelled Joiners
//   - Documentation > Task For Documentation
//   - Home > Dashboard
//   - Owner > List of Owner
//   - Report > Signoff Data Reports

const schema = new mongoose.Schema(
  {
    _mysqlId: { type: Number, index: true },
    vessel_id: Number,
    vesselname: String,
    company_name: String,
    call_sign: String,
    IMO_Number: String,
    gross_tonage: String,
    vessel_code: String,
    vessel_category: String,
    vesseltype: String,
    grt: String,
    bhp: String,
    bhp2: String,
    Flag: String,
    dg_date: String,
    cdagreement: String,
    seagreement: String,
    pipolicynumber: String,
    policydateofv: String,
    pipolicydocument: String,
    mlccertificateno: String,
    dofmlccertificate: String,
    doexpiry: String,
    maritimelabourconvention: String,
    fsdnumber: String,
    fsdvalidity: String,
    fsdocument: String,
    dmlcp1: String,
    dmlc2: String,
    odp: String,
    idp: String,
    cdp: String,
    rdp: String,
    copp: String,
    cdrp: String,
    status: String,
    remark: String,
    doneby: String,
    category: String,
    cdate: String,
    v_email: String,
    vset_no: Number,
    letterexplanation: String,
    cargo_pass: String,
  },
  { strict: false, collection: 'collection_vessel' }
);

export const LegacyVessel = mongoose.models.LegacyVessel || mongoose.model('LegacyVessel', schema);
